// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package domain

type CreateCommentInput struct {
	Author   string  `json:"author"`
	Text     string  `json:"text"`
	PostID   string  `json:"postId"`
	ParentID *string `json:"parentId,omitempty"`
}

type CreatePostInput struct {
	Title         string `json:"title"`
	Content       string `json:"content"`
	Author        string `json:"author"`
	AllowComments bool   `json:"allowComments"`
}

type Mutation struct {
}

type PageInfo struct {
	HasNextPage bool    `json:"hasNextPage"`
	EndCursor   *string `json:"endCursor,omitempty"`
}

type PostConnection struct {
	Edges    []*PostEdge `json:"edges"`
	PageInfo *PageInfo   `json:"pageInfo"`
}

type PostEdge struct {
	Node   *Post  `json:"node"`
	Cursor string `json:"cursor"`
}

type Query struct {
}

type Subscription struct {
}
